[project]
name = "orvyn"
version = "0.1.0"
description = "Add your description here"
authors = [{ name = "Your Name", email = "your@email.com" }]
readme = "README.md"
requires-python = ">=3.10"
dependencies = []
